### ISSUE TITLE
Docker

### ISSUE THREAD

**Issue by otmpp** [dakusan/PlexPlaylistImporter#20] opened 2021-08-04 11:12 UTC
I would like to use this with my plex server. However I'm not sure how to use it on my server? 
It's debian and running through docker.
Can it be used the same?

Thank you

**Comment by dakusan** [comment] 2021-08-04 20:03
It's a Python script. Nothing from stopping you using it on Docker.

**Comment by otmpp** [comment] 2021-08-05 11:52
Okay I have been trying to run it. My playlist are saved as m3u8 so I have edited them to have the same path to the music as what the docker sees it as yet I get an error : DB Error: unknown tokenizer: collating

What do I need to do?

**Comment by dakusan** [comment] 2021-08-10 18:58
https://github.com/dakusan/PlexPlaylistImporter/issues/18#issuecomment-820019654

**Comment by dakusan** [comment] 2023-09-11 01:38
This is a duplicate of issue #18

**Closed as completed by dakusan** 2023-09-11 01:38 UTC
